### ISSUE TITLE
~conexão do container novosga x msyql

### ISSUE THREAD

**Issue by rjunior069** [novosga/docker#13]
boa noite estou instalando novosga na versão 2.1 com msyql 9.1,
porem  sempre estou esbarrando no error abaixo, alguém consegue ajudar, ja passaram por isso? alguma sugestão?

```
Starting pre-flight check...
Database url: Ok

 // Clearing the cache for the prod environment with debug
 // false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


 // Warming up the cache for the prod environment with debug
 // false

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.

Waiting for database...
Waiting for database...
Waiting for database...
```

**Comment by rogeriolino** [comment]
A partir do MySQL 8, a forma de autenticação foi alterada. Causando incompatibilidade com o driver de conexão do PHP.

Utilize o MySQL 5.7 ou crie um usuário com método de autenticação legado.

**Comment by rjunior069** [comment]
Bom dia @rogeriolino 
[root@labs dados]#  podman run -d --name novosga -p 4010:80 -p 2020:2020 -e DATABASE_URL='mysql://novosga:xxxxx@localhost:3307/novosgadb?charset=utf8mb4&serverVersion=5.7' localhost/novosga && podman logs -f novosga
c98d175bc17df4e42bb053321288a64306d3d9e67eaaa988f3c3b3c6402b9564
Starting pre-flight check...
Database url: Ok

 // Clearing the cache for the prod environment with debug
 // false

 [OK] Cache for the "prod" environment (debug=false) was successfully cleared.


 // Warming up the cache for the prod environment with debug
 // false

 [OK] Cache for the "prod" environment (debug=false) was successfully warmed.

Waiting for database...
Waiting for database...
Waiting for database...
Waiting for database...
Waiting for database...



nada ainda, será o banco tem que ser fisico?

e obrigado pelo feedback

**Comment by rjunior069** [comment]
@rogeriolino  consegui resolver, tive que subi o container no ip da maquina virtual, agora esta dando problema de FK ao migrar o dump de um lado para outro.
 dados para banco

**Comment by rogeriolino** [comment]
@rjunior069 ei Reinaldo, pelo visto o seu problema era na URL de conexão. 

Já que a imagem docker está funcionando corretamente e você está enfrentando outro problema agora (relacionado a migração de dados), vou fechar esta Issue e você pode usar o fórum para ver essa dúvida sobre migração: https://discuss.novosga.org/

Att.
