### ISSUE TITLE
Websocket server

### ISSUE THREAD

**Issue by rogeriolino** [novosga/docker#3]
Start websocket server.

| Script | Argument |
| -------- | ------------- |
| /var/www/html/bin/console novosga:websocket | start |

**Idea:**

Change image entrypoint/command to `supervisor` service and put two supervidor conf files to starts `apache2-foreground` and `websocket script`.

    CMD ["/usr/bin/supervisord"]

**/etc/supervisor/conf.d/apache2.conf**

```
[program:apache2]
command = docker-php-entrypoint apache2-foreground
```

**/etc/supervisor/conf.d/websocket.conf**

```
[program:websocket-server]
command = /var/www/html/bin/console novosga:websocket start
```

**Comment by rogeriolino** [comment]
@somatorio any suggestion?

**Comment by somatorio** [comment]
well, i think we can set start.sh to call for supervisord instead of apache2-foreground... 
i'll test it out and see our options :)

**Comment by rogeriolino** [comment]
Created Symfony command to wrap websocket script:

    bin/console novosga:websocket status
    bin/console novosga:websocket start
    bin/console novosga:websocket stop

**Comment by rogeriolino** [comment]
9188456840060afcabf0047ab0a400afc8388107
