### ISSUE TITLE
Timezone support

### ISSUE THREAD

**Issue by rogeriolino** [novosga/docker#4]
To provide easy way to configure PHP timezone.

**Example:**

Create `novosga.ini` file into `/usr/local/etc/php/conf.d` with `date.timezone` value from environment variable.

**Comment by somatorio** [comment]
that's already in the image :)
from Dockerfile:

```shell
echo 'date.timezone = ${TZ}' > /usr/local/etc/php/conf.d/datetimezone.ini
```

And this is specified at README.md as well, the "TZ" environment variable (https://www.cyberciti.biz/faq/linux-unix-set-tz-environment-variable/) sets this :)

**Comment by rogeriolino** [comment]
I've not seen it on Dockerfile.

Thanks.
