### ISSUE TITLE
start.sh: not found

### ISSUE THREAD

**Issue by rafaelsoaresbr** [novosga/docker#6]
Hello guys, I'm getting the following error after building this image (using docker toolbox):

```
# docker build -t novosga:built .
# docker-compose up
```

> novosga_1  | /usr/local/bin/docker-php-entrypoint: 9: exec: start.sh: not found

docker-compose.yml is the same as in [README.md](https://github.com/novosga/docker/blob/master/novosga-2.0/README.md) but using novosga:built (obviously).

```
# docker info
```

>Containers: 5
 Running: 0
 Paused: 0
 Stopped: 5
Images: 36
Server Version: 17.12.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 127
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.108-boot2docker
Operating System: Boot2Docker 17.12.0-ce (TCL 8.2.1); HEAD : 378b049 - Wed Dec 27 23:39:20 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.9MiB
Name: default
ID: KNPW:GVYK:3E7Q:3PHH:5PJP:HQV5:RFE4:TLHE:Q5XO:DBJF:EOEM:L3RV
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 19
 Goroutines: 34
 System Time: 2018-03-28T04:11:18.753609441Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by rogeriolino** [comment]
1) Did you make any change in the `novosga-2.0/Dockerfile`?

2) Are you using Windows? Windows loses Linux filemode.

Run your container bash:

    docker run -it --rm novosga:built /bin/bash

Check if start.sh file exists (and can exec):

    ls -lha /usr/local/bin/start.sh

**Comment by rafaelsoaresbr** [comment]
1. No
2. Yes, Docker Toolbox

start.sh is there.
-rwxr-xr-x  1 root root       904 Mar 28 03:04 start.sh

**Comment by BahrouniYousra** [comment]
How whould you change the ending line to LF insted of CRLF please !
