### ISSUE TITLE
Erro ao exibir detalhes da senha no módulo monitor

### ISSUE THREAD

**Issue by lamasbr** [novosga/docker#8]
Boa noite!

Primeiramente, parabéns e obrigado pelo projeto Novo SGA. Utilizamos a versão 1.5.1 em um órgão público de Minas Gerais para atendimento e distribuição de medicamentos de alto custo para a população.

Baixei a versão em docker e ao efetuar alguns testes, percebi que ao acessar o módulo Monitor e clicar sobre uma senha qualquer (quando cadastrado um atendimento informando documento e nome da pessoa), na tabela que exibe as informações, onde deveria estar escrito DOCUMENTO, está escrito NOME, como pode-se observar na imagem abaixo:

![2018-10-05 22_59_01-monitor_ novo sga ce](https://user-images.githubusercontent.com/668513/46566359-3107c100-c8f3-11e8-82b7-8923b7b59408.png)

Além disso, a data da chegada está sendo exibida sem a indicação AM/PM ou com o horário errado mesmo, já que nesse teste, a hora da chegada deveria ser 22:53:31.

**Comment by e-ruiz** [comment]
Rodando o Docker com NovoSGA 2.0.8 aqui hoje (26/12/2019) e tive problemas com horário de verão, que na verdade tem que ser UTC -2 e não UTC -3, já que não temos mais horário de verão. Como solução, em ambiente de testes, apenas entrei no container e atualizei o tzdata com a variável de ambiente TZ=America/Sao_Paulo e já corrigiu o horário no container de aplicação.

Já o container do MySQL já estava OK.
